spring:
  application:
    name: "customer"

  profiles:
    active: "prod"

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ' '

    test:
      url: jdbc:h2:mem/unit_test_db
      diver-class-name: org.h2.Driver
      username: sa
      password: ' '
      hibernate:
        ddl-auto : update

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  management:
    endpoints:
      web:
        exposure:
          include: "*"

    endpoint:
      health:
        show-details: "always"

  config:
    import: "optional:configserver:http://localhost:8071/"

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"


server:
    port: 8181

